### ISSUE TITLE
Any luck this year?

### ISSUE THREAD

**Issue by frazerf** [jps/glasto-smasher#1]
Not an issue but just wondering if you had any success in the coach sale ticket sales? @jps

**Comment by jps** [comment]
hey @frazerf , did manage to get past the holding page with this but wasn't able to get the tickets in to the basket as suspect most had been allocated by that point! Luckily our mate secured some on his phone... Just shows that there is still a big luck element!

RE the script, I think it will improve odds but It's a bit of balance of how fast to let it run because I suspect you will get rate limited at a certain point... I added a `--delay` option for this, I've defaulted it to `1200` ms but suspect you could go lower 

 My tip would be try multiple devices and get as many of you friends trying also, good luck on Sunday!

**Comment by frazerf** [comment]
Thanks for getting back to me @jps - past the holding page is further than I got using my phone and two computers so that's promising. Cheers for the script and congratulations on securing tickets through your friend. I'll owe you a beer if the this works!
